In [2]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import numpy as np
import torch

In [3]:
BASE_DIR = Path("/Users/gryv9001/code/nielsen/pacing-target-creation/data/raw/")
TRAIN_FILE = BASE_DIR / "train/Monthly-train.csv"

In [4]:
print(str(TRAIN_FILE))

/Users/gryv9001/code/nielsen/pacing-target-creation/data/raw/train/Monthly-train.csv


In [5]:
#data = pd.read_csv(str(DATA_FILE))

In [6]:
#data.head()

In [11]:
w1 = torch.randn(1, 20, device="cpu", dtype=torch.float32)
h = 5

In [13]:
w1

tensor([[-0.6773,  2.2022,  0.4446, -1.1195,  1.3222, -1.3104,  0.6838,  1.0652,
         -0.4307,  0.4668, -1.0333,  0.1058,  0.0088,  0.2930, -0.1976, -0.3930,
          0.9679,  1.9270,  0.6173, -2.0534]])

In [20]:
w1[:,:-h]

tensor([[-0.6773,  2.2022,  0.4446, -1.1195,  1.3222, -1.3104,  0.6838,  1.0652,
         -0.4307,  0.4668, -1.0333,  0.1058,  0.0088,  0.2930, -0.1976]])

In [21]:
w1[:,h:]

tensor([[-1.3104,  0.6838,  1.0652, -0.4307,  0.4668, -1.0333,  0.1058,  0.0088,
          0.2930, -0.1976, -0.3930,  0.9679,  1.9270,  0.6173, -2.0534]])

In [23]:
torch.mean(torch.abs(w1[:,:-h] - w1[:,h:]))

tensor(0.8811)